[project]
name = "gpu-experiments"
version = "0.1.0"
description = "Experiments with GPU programming"
requires-python = ">=3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 88
